#ifndef EEPROM_LAYOUT_H_INCLUDED
#define EEPROM_LAYOUT_H_INCLUDED

#define EEPROM_LAYOUT_VERSION 1
#define AMOUNT_OF_INDEXES (sizeof(bool) + sizeof(size_t) + Configuration_size)

#define INDEX_EEPROM_INIT 0
#define INDEX_CONFIGURATION_BUFFER_SIZE (INDEX_EEPROM_INIT+sizeof(bool))
#define INDEX_CONFIGURATION (INDEX_CONFIGURATION_BUFFER_SIZE+sizeof(size_t))

#endif