#ifndef EEPROM_LAYOUT_H_INCLUDED
#define EEPROM_LAYOUT_H_INCLUDED

#define EEPROM_LAYOUT_VERSION 0
#define AMOUNT_OF_INDEXES 3

#define INDEX_EEPROM_INIT 0
#define INDEX_CONFIGURATION 1
#define INDEX_CONFIGURATION_BUFFER_SIZE 2

#endif